spring:
  profiles:
    active: prod

  datasource:
    url: jdbc:mysql://mysql_1:3306/app_prod?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: appuser
    password: lldj123414
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        highlight_sql: false
        use_sql_comments: false

  data:
    redis:
      host: redis_1
      port: 6379
      password: lldj123414

  security:
    oauth2:
      client:
        registration:
          kakao:
            clientId: ${KAKAO_CLIENT_ID}
            scope: profile_nickname, profile_image
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: '{baseUrl}/login/oauth2/code/kakao'
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

logging:
  level:
    com.back: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN
    org.hibernate.orm.jdbc.extract: WARN
    org.springframework.transaction.interceptor: WARN

custom:
  prod:
    domain: "mypractice.store"
    backUrl: "https://api.mypractice.store"
    frontUrl: "https://mypractice.store"

  site:
    domain: "${custom.prod.domain}"
    backUrl: "${custom.prod.backUrl}"
    frontUrl: "${custom.prod.frontUrl}"

  jwt:
    expireSeconds: "#{30 * 60}"
    secretPattern: ${CUSTOM_JWT_SECRET_PATTERN}
